name: Review Dependencies

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 10.16.3
        
    - name: Restore dependencies
      run: dotnet restore ./Source/Tailwind.Traders.Web.sln
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v4.8.0
      with:
        comment-summary-in-pr: always
        show-openssf-scorecard: true
          
